---
# Create: simple-k3s-install.yml
- name: Simple K3s Cluster Installation
  hosts: k3s_cluster
  become: yes
  vars_files:
    - secrets.yml
  vars:
    k3s_version: "v1.28.9+k3s1"
    k3s_server_ip: "{{ hostvars['node-01']['ansible_host'] }}"
    
  tasks:
    - name: Install K3s server
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="{{ k3s_version }}" sh -s - server --cluster-init
      when: inventory_hostname == 'node-01'
      
    - name: Wait for K3s server to be ready
      ansible.builtin.wait_for:
        port: 6443
        host: "{{ k3s_server_ip }}"
        timeout: 60
      when: inventory_hostname == 'node-01'
      
    - name: Get node token
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token
      when: inventory_hostname == 'node-01'
      
    - name: Install K3s agents
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="{{ k3s_version }}" \
        K3S_URL=https://{{ k3s_server_ip }}:6443 \
        K3S_TOKEN="{{ hostvars['node-01']['node_token']['content'] | b64decode | trim }}" sh -
      when: inventory_hostname != 'node-01'
      
    - name: Verify cluster
      ansible.builtin.command: kubectl get nodes
      register: cluster_nodes
      when: inventory_hostname == 'node-01'
      
    - name: Show cluster status
      ansible.builtin.debug:
        var: cluster_nodes.stdout_lines
      when: inventory_hostname == 'node-01'